// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 4ek7yevYSmZU9MaEHzjjyJ
// Component: DyM3o4afMIzM
import * as React from "react";
import { useRouter } from "next/router";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 4ek7yevYSmZU9MaEHzjjyJ/projectcss
import sty from "./PlasmicHalcyonFooterBottom.module.css"; // plasmic-import: DyM3o4afMIzM/css

createPlasmicElementProxy;

export const PlasmicHalcyonFooterBottom__VariantProps = new Array();

export const PlasmicHalcyonFooterBottom__ArgProps = new Array();

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicHalcyonFooterBottom__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );
  const $props = {
    ...args,
    ...variants
  };
  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  return (
    <div
      data-plasmic-name={"halcyonFooterBottom"}
      data-plasmic-override={overrides.halcyonFooterBottom}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.halcyonFooterBottom
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"\u00a9 HalcyonStudios. All rights reserved."}
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  halcyonFooterBottom: ["halcyonFooterBottom", "text"],
  text: ["text"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHalcyonFooterBottom__ArgProps,
          internalVariantPropNames: PlasmicHalcyonFooterBottom__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHalcyonFooterBottom__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "halcyonFooterBottom") {
    func.displayName = "PlasmicHalcyonFooterBottom";
  } else {
    func.displayName = `PlasmicHalcyonFooterBottom.${nodeName}`;
  }
  return func;
}

export const PlasmicHalcyonFooterBottom = Object.assign(
  // Top-level PlasmicHalcyonFooterBottom renders the root element
  makeNodeComponent("halcyonFooterBottom"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),
    // Metadata about props expected for PlasmicHalcyonFooterBottom
    internalVariantProps: PlasmicHalcyonFooterBottom__VariantProps,
    internalArgProps: PlasmicHalcyonFooterBottom__ArgProps
  }
);

export default PlasmicHalcyonFooterBottom;
/* prettier-ignore-end */
